app = ""

kill_signal = "SIGINT"
kill_timeout = "15s"
# swap cannot be used with "suspend"
# community.fly.io/t/20672
# swap_size_mb = 152

[build]
  dockerfile = "node.Dockerfile"

[experimental]
  auto_rollback = true

[env]
  CLOUD_PLATFORM = "fly"
  BUN_ENV = "production"
  DENO_ENV = "production"
  NODE_ENV = "production"
  LOG_LEVEL = "info"
  # in weeks
  AUTO_RENEW_BLOCKLISTS_OLDER_THAN = "2"

# community.fly.io/t/19180
# fly.io/docs/machines/guides-examples/machine-restart-policy
[[restart]]
  policy = "on-failure"
  retries = 3

# DNS over HTTPS
[[services]]
  protocol = "tcp"
  internal_port = 8080
  auto_stop_machines = "suspend"
  auto_start_machines = true

  [[services.ports]]
    # TODO: ProxyProto v2
    port = 443
  [[services.ports]]
    port = 8080

  [services.concurrency]
    type = "connections"
    hard_limit = 775
    soft_limit = 600

  [[services.tcp_checks]]
    # super aggressive interval and timeout because
    # health-check routing is handled by fly-proxy
    # and it is cross-region
    # community.fly.io/t/12997
    interval = "5s"
    timeout = "1s"
    grace_period = "15s"
    # restart_limit not used on appsv2
    restart_limit = 0

# DNS over TLS
[[services]]
  protocol = "tcp"
  internal_port = 10000
  auto_stop_machines = "suspend"
  auto_start_machines = true

  [[services.ports]]
    # TODO: ProxyProto v2
    port = 853
  [[services.ports]]
    port = 10000

  [services.concurrency]
    type = "connections"
    hard_limit = 775
    soft_limit = 600

  [[services.tcp_checks]]
    # super aggressive interval and timeout because
    # health-check routing is handled by fly-proxy
    # and it is cross-region
    # community.fly.io/t/12997
    interval = "5s"
    timeout = "1s"
    grace_period = "15s"
    # restart_limit is unused in appsv2
    restart_limit = 0

# community.fly.io/t/5490/3
[checks]
  [checks.up]
    # grace_period affects time taken for rolling deploys
    grace_period = "15s"
    interval = "15s"
    method = "get"
    path = "/check"
    port = 8888
    timeout = "2s"
    type = "http"
